// Demo data used when Supabase is not configured (preview mode).
// Mirrors the exact data shown in the approved template designs.

export const demoCandidates = [
  {
    id: 'c1',
    name: 'AMINA ALI KAKAWA',
    position: 'DOMESTIC WORKER',
    company: 'No company',
    salary: 'KWD 1,100.000',
    email: '1793949273605@temp.com',
    phone: '+000 000 0000',
    stage: 'Onboarding',
    status: 'Onboarding',
    country_applying_to: 'Kuwait',
    created_at: '2024-01-10T08:00:00Z',
    updated_at: '2024-01-10T08:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c2',
    name: 'AMINA ALI KAKAWA',
    position: 'DOMESTIC WORKER',
    company: 'No company',
    salary: 'KWD 1,100.000',
    email: '1793949141350@temp.com',
    phone: '+000 000 0000',
    stage: 'Onboarding',
    status: 'Onboarding',
    country_applying_to: 'Kuwait',
    created_at: '2024-01-09T08:00:00Z',
    updated_at: '2024-01-09T08:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c3',
    name: 'AMINA ALI KAKAWA',
    position: 'DOMESTIC WORKER',
    company: 'No company',
    salary: 'KWD 1,100.000',
    email: '1793949037105@temp.com',
    phone: '+000 000 0000',
    stage: 'Onboarding',
    status: 'Onboarding',
    country_applying_to: 'Kuwait',
    created_at: '2024-01-08T08:00:00Z',
    updated_at: '2024-01-08T08:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c4',
    name: 'LYDIA MAPENZI KITSAO',
    position: 'DOMESTIC WORKER',
    company: 'No company',
    salary: 'KWD 1,100.000',
    email: '1793940210890@temp.com',
    phone: '+000 000 0000',
    stage: 'Onboarding',
    status: 'Onboarding',
    country_applying_to: 'Kuwait',
    created_at: '2024-01-07T08:00:00Z',
    updated_at: '2024-01-07T08:00:00Z',
    deleted_at: null,
  },
  {
    id: 'c5',
    name: 'LYDIA MAPENZI KITSAO',
    position: 'DOMESTIC WORKER',
    company: 'No company',
    salary: 'KWD 1,100.000',
    email: '1793940145034@temp.com',
    phone: '+000 000 0000',
    stage: 'Onboarding',
    status: 'Onboarding',
    country_applying_to: 'Kuwait',
    created_at: '2024-01-06T08:00:00Z',
    updated_at: '2024-01-06T08:00:00Z',
    deleted_at: null,
  },
]

export const demoTotalCandidates = 165

export const demoJobs = [
  {
    id: 'j1',
    title: 'Cleaners',
    company: 'Naim Investments',
    location: 'Dammam, Saudi Arabia',
    country: 'Saudi Arabia',
    type: 'full-time',
    salary_min: 0,
    salary_max: 0,
    currency: 'SAR',
    status: 'Active',
    posted_date: '2025-09-22',
    created_at: '2025-09-22T08:00:00Z',
    deleted_at: null,
  },
  {
    id: 'j2',
    title: 'Personal Driver (Female)',
    company: 'Elite Chauffeur Services',
    location: 'Kuwait City, Kuwait',
    country: 'Kuwait',
    type: 'Full-time',
    salary_min: 350,
    salary_max: 450,
    currency: 'KWD',
    status: 'Closed',
    posted_date: '2024-01-07',
    created_at: '2024-01-07T08:00:00Z',
    deleted_at: null,
  },
]

export const demoTasks = [
  {
    id: 't1',
    title: 'Follow up with Qatar Medical Center',
    assignee: 'John Recruiter',
    category: 'Follow-up',
    priority: 'HIGH',
    due_date: '2024-01-23',
    created_by: 'Admin',
    status: 'Completed',
  },
  {
    id: 't2',
    title: 'Schedule Medical Exam for James Omondi',
    assignee: 'Sarah Coordinator',
    category: 'Medical',
    priority: 'MEDIUM',
    due_date: '2024-01-24',
    created_by: 'Admin',
    status: 'In Progress',
  },
]

export const demoNotifications = [
  {
    id: 'n1',
    title: 'Follow up with Qatar Medical Center due tomorrow',
    time: '2 hours ago',
    tags: [
      { label: 'high', color: 'bg-red-100 text-red-600' },
      { label: 'task', color: 'bg-blue-100 text-blue-600' },
    ],
    read: false,
  },
  {
    id: 'n2',
    title: 'James Omondi has updated his profile',
    time: '1 day ago',
    tags: [
      { label: 'medium', color: 'bg-yellow-100 text-yellow-700' },
      { label: 'candidate', color: 'bg-green-100 text-green-600' },
    ],
    read: false,
  },
  {
    id: 'n3',
    title: 'Interview with Jane Mwangi scheduled for tomorrow at 10:00 AM',
    time: '3 hours ago',
    tags: [
      { label: 'high', color: 'bg-red-100 text-red-600' },
      { label: 'appointment', color: 'bg-purple-100 text-purple-600' },
    ],
    read: false,
  },
]
